
{{ if ( ne .Values.unittests true ) }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:

      containers:
        - name: api
          image: {{ .Values.registry }}api:{{ .Values.tags.api  }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}

          resources:
            requests:
              memory: 2000Mi
              cpu: 600m
            limits:
              memory: 3000Mi
              cpu: 2000m

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 5500
      targetPort: 5500
      name: http
      nodePort: 30600
  type: NodePort

{{ end }}
