### UI FRONTEND ###

{{ if ( ne .Values.unittests true ) }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
      metadata:
        labels:
          app: webapp
      spec:
        containers:
          - name: app
            image: {{ .Values.registry }}webapp:{{ .Values.tags.webapp  }}
            imagePullPolicy: {{ .Values.imagePullPolicy }}
            resources:
{{ if ( eq .Values.environment "development" ) }}
              requests:
                memory: 4000Mi
                cpu: 2000m
              limits:
                memory: 6000Mi
                cpu: 4000m
{{ else }}
              requests:
                memory: 200Mi
                cpu: 200m
              limits:
                memory: 300Mi
                cpu: 1000m
{{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
      name: http
      nodePort: 30500
  type: NodePort

{{ end }}